### ISSUE TITLE
accessing client cache

### ISSUE THREAD

**Issue by IllusionElements** [cult-of-coders/apollo#56]
for the client side, is there anyway to get the cache or add our own cache to initialize, just wondering since i'm using apollo-link-state and it requires a cache to be passed into it's initialization.

**Comment by yellowspaceboots** [comment]
I have been passing my state link into the client as normal. stateLink is created the same on my Meteor client and my React Native client and both work as you would expect from the apollo-link-state docs
```
const defaults = merge(CoreDefaultState)
const resolvers = merge(CoreResolvers)

const stateLink = withClientState({
  resolvers,
  defaults,
  cache,
  typeDefs
})

const link = ApolloLink.from([stateLink, authLink, wsHttpSplitLink])

const client = new ApolloClient({
  link,
  cache
})
```

**Comment by IllusionElements** [comment]
> I have been passing my state link into the client as normal. stateLink is created the same on my Meteor client and my React Native client and both work as you would expect from the apollo-link-state docs
> 
> ```
> const defaults = merge(CoreDefaultState)
> const resolvers = merge(CoreResolvers)
> 
> const stateLink = withClientState({
>   resolvers,
>   defaults,
>   cache,
>   typeDefs
> })
> 
> const link = ApolloLink.from([stateLink, authLink, wsHttpSplitLink])
> 
> const client = new ApolloClient({
>   link,
>   cache
> })
> ```

does it still work with meteor-apollo-accounts? I was worried perhaps something would break if I were to pass it onto ApolloClient instead of initialize

**Comment by yellowspaceboots** [comment]
Yes I am using meteor-apollo-accounts in my React Native application. apollo-link-state works fine if you set it up according to the apollo-link-state docs. That's one thing I love about the links that apollo has is that you can chain them together. Since the cult of coders apollo set up doesn't deal with local state you can just add apollo-link-state in and it works as expected. And since apollo-link-state passes the cache via context as long as you set a user object in your apollo cache you can access it via the context.cache in your state resolvers.

One thing I will point out though is when I updated to meteor 1.8 I am no longer getting the full user object in my resolver context. I opened up an issue here on github but just be aware that if you're in meteor 1.8 you can still access context.user._id but the rest of the user object is missing for some reason and I have not figured out why. I just do `const user = meteor.user.findOne(context.user._id)` to get my full user object in my resolvers until I can figure out why this is happening.

Hope this helps!

**Comment by theodorDiaconu** [comment]
Custom client should be made by yourself. Just copy it from the branch. We don't want to add a lot of logic to the client initialiser when it's just simpler to copy/paste and adapt it.
